name: eni

channels:
  - defaults
  - conda-forge

dependencies:
  - tqdm=4.59.0
  - numpy=1.20.1
  - shapely=1.7.1
  - scikit-geometry=0.1.2
  - bokeh=2.3.2
  - pip
  - pip:
    - scipy==1.6
    - triangle==20200424
    - geompreds==1.0.2